export const SEARCHABLES = {
  users: {
    columns: [
      'id',
      'uuid',
      'person_id',
      'username',
      'email',
      'phone',
      'status',
      'role',
      'last_login_at',
      'email_verified_at',
      'phone_verified_at',
      'created_at',
      'updated_at',
      'deleted_at',
    ],
    filters: [
      'id',
      'uuid',
      'person_id',
      'username',
      'email',
      'phone',
      'status',
      'role',
      'created_at',
      'updated_at',
      'deleted_at',
    ],
    orderBy: [
      'id',
      'username',
      'email',
      'status',
      'role',
      'created_at',
      'updated_at',
    ],
    includes: ['person', 'metas'],
    meta: {
      table: 'user_meta',
      foreignKey: 'user_id',
      allowedKeys: ['timezone', 'notifications', 'theme', 'locale'],
    },
  },

  persons: {
    columns: [
      'id',
      'uuid',
      'full_name',
      'display_name',
      'birth_date',
      'phone',
      'email',
      'gender',
      'status',
      'notes',
      'created_at',
      'updated_at',
      'deleted_at',
    ],
    filters: [
      'id',
      'uuid',
      'full_name',
      'display_name',
      'birth_date',
      'phone',
      'email',
      'gender',
      'status',
      'created_at',
      'updated_at',
      'deleted_at',
    ],
    orderBy: [
      'id',
      'full_name',
      'display_name',
      'email',
      'status',
      'created_at',
      'updated_at',
    ],
    includes: ['users', 'metas'],
    meta: {
      table: 'person_meta',
      foreignKey: 'person_id',
      allowedKeys: ['nickname', 'is_customer', 'segment', 'city'],
    },
  },
} as const

export type SearchableResource = keyof typeof SEARCHABLES