version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333" # Mapeia a porta 3333 do host para a porta 3333 do contêiner
    volumes:
      - .:/app # Monta o diretório atual do projeto dentro do contêiner
      - /app/node_modules # Garante que os node_modules instalados no contêiner não sejam sobrescritos pelo host
    command: ["node", "ace", "serve", "--watch"] # Comando para iniciar o serviço da API
    environment:
      - NODE_ENV=development
    restart: unless-stopped # Reinicia o contêiner automaticamente, a menos que seja parado manualmente

  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Monta o diretório atual do projeto dentro do contêiner
      - /app/node_modules # Garante que os node_modules instalados no contêiner não sejam sobrescritos pelo host
    command: ["node", "ace", "webhook:worker"] # Comando para iniciar o serviço do webhook
    environment:
      - NODE_ENV=development
    restart: unless-stopped # Reinicia o contêiner automaticamente, a menos que seja parado manualmente