/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class NotificationMessageLogSchema extends BaseModel {
  static $columns = ['context', 'createdAt', 'id', 'message', 'notificationMessageId', 'status', 'tenantId', 'type'] as const
  $columns = NotificationMessageLogSchema.$columns
  @column()
  declare context: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare notificationMessageId: number
  @column()
  declare status: string | null
  @column()
  declare tenantId: number
  @column()
  declare type: string
}

export class NotificationMessageSchema extends BaseModel {
  static $columns = ['attempts', 'channel', 'content', 'createdAt', 'deletedAt', 'deliveredAt', 'externalId', 'failedAt', 'id', 'lastAttemptAt', 'nextRetryAt', 'notificationId', 'provider', 'providerConfigTag', 'providerResponse', 'readAt', 'renderedPayload', 'retryLimit', 'sentAt', 'status', 'subject', 'tenantId', 'to', 'updatedAt'] as const
  $columns = NotificationMessageSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare channel: string
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare externalId: string | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastAttemptAt: DateTime | null
  @column.dateTime()
  declare nextRetryAt: DateTime | null
  @column()
  declare notificationId: number
  @column()
  declare provider: string | null
  @column()
  declare providerConfigTag: string | null
  @column()
  declare providerResponse: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare renderedPayload: any | null
  @column()
  declare retryLimit: number
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare tenantId: number
  @column()
  declare to: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationTemplateItemTranslationSchema extends BaseModel {
  static $columns = ['caption', 'content', 'createdAt', 'deletedAt', 'id', 'locale', 'mediaUrl', 'notificationTemplateItemId', 'subject', 'tenantId', 'updatedAt', 'uuid'] as const
  $columns = NotificationTemplateItemTranslationSchema.$columns
  @column()
  declare caption: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare mediaUrl: string | null
  @column()
  declare notificationTemplateItemId: number
  @column()
  declare subject: string | null
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class NotificationTemplateItemSchema extends BaseModel {
  static $columns = ['channel', 'contentType', 'createdAt', 'delayMs', 'deletedAt', 'id', 'isActive', 'mediaType', 'notificationTemplateId', 'sortOrder', 'tenantId', 'type', 'updatedAt', 'uuid'] as const
  $columns = NotificationTemplateItemSchema.$columns
  @column()
  declare channel: string | null
  @column()
  declare contentType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delayMs: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare mediaType: string | null
  @column()
  declare notificationTemplateId: number
  @column()
  declare sortOrder: number
  @column()
  declare tenantId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class NotificationTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'domain', 'id', 'isActive', 'key', 'name', 'tenantId', 'updatedAt', 'uuid'] as const
  $columns = NotificationTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare domain: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'deletedAt', 'eventKey', 'failedAt', 'id', 'notifiableId', 'notifiableType', 'payload', 'priority', 'recipient', 'recipientId', 'recipientName', 'recipientType', 'scheduledAt', 'sentAt', 'status', 'systemKey', 'templateId', 'tenantId', 'updatedAt', 'uuid'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare eventKey: string
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notifiableId: number | null
  @column()
  declare notifiableType: string | null
  @column()
  declare payload: any | null
  @column()
  declare priority: number
  @column()
  declare recipient: string
  @column()
  declare recipientId: number | null
  @column()
  declare recipientName: string | null
  @column()
  declare recipientType: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare systemKey: string | null
  @column()
  declare templateId: number | null
  @column()
  declare tenantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class PersonMetaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'personId', 'type', 'updatedAt', 'value'] as const
  $columns = PersonMetaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare personId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class PersonSchema extends BaseModel {
  static $columns = ['birthDate', 'createdAt', 'deletedAt', 'displayName', 'email', 'fullName', 'gender', 'id', 'notes', 'phone', 'status', 'updatedAt', 'uuid'] as const
  $columns = PersonSchema.$columns
  @column.date()
  declare birthDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare displayName: string | null
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'group', 'id', 'isPublic', 'key', 'tag', 'type', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublic: boolean
  @column()
  declare key: string
  @column()
  declare tag: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class TenantSchema extends BaseModel {
  static $columns = ['appConfigs', 'createdAt', 'deletedAt', 'id', 'name', 'secrets', 'slug', 'status', 'uiSettings', 'updatedAt', 'uuid'] as const
  $columns = TenantSchema.$columns
  @column()
  declare appConfigs: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare secrets: any | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare uiSettings: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class TicketWhatsappMessageSchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'deletedAt', 'filename', 'id', 'senderName', 'senderNumber', 'sentAt', 'status', 'ticketNumber', 'updatedAt', 'validationCode', 'whatsappMessageId'] as const
  $columns = TicketWhatsappMessageSchema.$columns
  @column()
  declare attempts: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare filename: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare senderName: string | null
  @column()
  declare senderNumber: string
  @column.dateTime()
  declare sentAt: DateTime
  @column()
  declare status: string
  @column()
  declare ticketNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare validationCode: string
  @column()
  declare whatsappMessageId: string
}

export class TicketSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'eventId', 'id', 'status', 'ticketNumber', 'updatedAt', 'uuid', 'validatedAt', 'validationCode'] as const
  $columns = TicketSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare ticketNumber: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
  @column.dateTime()
  declare validatedAt: DateTime | null
  @column()
  declare validationCode: string | null
}

export class UserMetaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'type', 'updatedAt', 'userId', 'value'] as const
  $columns = UserMetaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'emailVerifiedAt', 'id', 'lastLoginAt', 'password', 'personId', 'phone', 'phoneVerifiedAt', 'rememberMeToken', 'role', 'status', 'updatedAt', 'username', 'uuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare personId: number | null
  @column()
  declare phone: string | null
  @column.dateTime()
  declare phoneVerifiedAt: DateTime | null
  @column()
  declare rememberMeToken: string | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
  @column()
  declare uuid: string
}
